# Unique project key recognized by SonarQube dashboard
sonar.projectKey=devsecops-app

# Project display name shown in the SonarQube UI
sonar.projectName=SrinuTechGuru DevSecOps NodeJS App

# Path to the source code you want scanned
sonar.sources=src

# Encoding format for source files
sonar.sourceEncoding=UTF-8
